# -*- coding: utf-8 -*-
"""
Created on Mon Aug  5 21:05:41 2019

@author: David
"""

partypes = {
        'LULC':'TEXT',
        'HRU': 'NUMERIC',
        'GIS': 'NUMERIC',
        'SUB': 'NUMERIC',
        'MGT': 'NUMERIC',
        'MO': 'NUMERIC',
         'DA': 'NUMERIC',
           'YR': 'NUMERIC',
           'AREAkm2': 'NUMERIC',
          'PRECIPmm': 'NUMERIC',
         'SNOFALLmm' : 'NUMERIC',
        'SNOMELTmm': 'NUMERIC',
        'IRRmm': 'NUMERIC',
         'PETmm': 'NUMERIC',
        'ETmm': 'NUMERIC',
         'SW_INITmm': 'NUMERIC',
         'SW_ENDmm': 'NUMERIC',
        'PERCmm': 'NUMERIC',
        'GW_RCHGmm': 'NUMERIC',
         'DA_RCHGmm': 'NUMERIC',
         'REVAPmm': 'NUMERIC',

        'SA_IRRmm': 'NUMERIC',
         'DA_IRRmm': 'NUMERIC',
          'SA_STmm': 'NUMERIC',
          'DA_STmm': 'NUMERIC',
        'SURQGENmm': 'NUMERIC',
         'SURQ_CNTmm': 'NUMERIC',
         'TLOSSmm': 'NUMERIC',
        'LATQGENmm': 'NUMERIC',

        'GW_Qmm': 'NUMERIC',
            'WYLDmm': 'NUMERIC',
           'DAILYCN': 'NUMERIC',
         'TMP_AVdgC': 'NUMERIC',
         'TMP_MXdgC': 'NUMERIC',
         'TMP_MNdg': 'NUMERIC',
        'CSOL_TMPdg': 'NUMERIC',
        'CSOLARMJ/m2': 'NUMERIC',

        'SYLDt/ha': 'NUMERIC',
         'USLEt/ha': 'NUMERIC',
        'N_APPkg/ha': 'NUMERIC',
        'P_APPkg/ha': 'NUMERIC',
        'NAUTOkg/ha': 'NUMERIC',
        'PAUTOkg/ha': 'NUMERIC',
        'NGRZkg/ha ': 'NUMERIC',
        'PGRZkg/ha': 'NUMERIC',

        'NCFRTkg/ha': 'NUMERIC',
        'PCFRTkg/ha': 'NUMERIC',
        'NRAINkg/ha': 'NUMERIC',
         'NFIXkg/ha': 'NUMERIC',
         'F-MNkg/ha': 'NUMERIC',
        'A-MNkg/ha': 'NUMERIC',
         'A-SNkg/ha': 'NUMERIC',
         'F-MPkg/ha': 'NUMERIC',

        'AO-LPkg/ha': 'NUMERIC',
        'L-APkg/ha': 'NUMERIC',
         'A-SPkg/ha': 'NUMERIC',
         'DNITkg/ha': 'NUMERIC',
          'NUPkg/ha': 'NUMERIC',
          'PUPkg/ha': 'NUMERIC',
        'ORGNkg/ha': 'NUMERIC',
         'ORGPkg/ha': 'NUMERIC',

        'SEDPkg/ha': 'NUMERIC',
        'NSURQkg/ha': 'NUMERIC',
        'NLATQkg/ha': 'NUMERIC',
        'NO3Lkg/ha': 'NUMERIC',
        'NO3GWkg/ha': 'NUMERIC',
        'SOLPkg/ha': 'NUMERIC',
         'P_GWkg/ha': 'NUMERIC',
         'W_STRS': 'NUMERIC',

        'TMP_STRS': 'NUMERIC',
           'N_STRS': 'NUMERIC',
            'P_STRS': 'NUMERIC',
          'BIOMt/ha': 'NUMERIC',
               'LAI': 'NUMERIC',
           'YLDt/ha': 'NUMERIC',
          'BACTPct': 'NUMERIC',
          'BACTLPct': 'NUMERIC',

        'WTAB': 'NUMERIC',
        'CLIm': 'NUMERIC',
        'WTAB': 'NUMERIC',
        'SOLm': 'NUMERIC',
             'SNOmm': 'NUMERIC',
         'CMUPkg/ha': 'NUMERIC',
        'CMTOTkg/ha': 'NUMERIC',
          'QTILEmm': 'NUMERIC',
        'TNO3kg/ha': 'NUMERIC',
         'LNO3kg/ha': 'NUMERIC',

        'GW_Q_Dmm': 'NUMERIC',
         'LATQCNTmm': 'NUMERIC',
         'TVAPkg/ha': 'NUMERIC'
        }